name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Zola Deploy to Pages
      uses: shalzz/zola-deploy-action@master
      env:
        TOKEN: ${{ secrets.TOKEN }}
